---
title: "Project Proposal"
author: "Tianqi Li"
date: "2024-11-05"
output: github_document
---

**The group members (names and UNIs)**  
Enju Zhang (ez2384), Xinyu Wang (xw2961), Tianqi Li (tl3279), Kehan Su (ks4186), Sihan Qiu (sq2266)

**The tentative project title**  
Food Access and Nutrition in NYC

**The motivation for this project**  
Food access contributes to health inequality. Therefore, the motivation for exploring “food access and nutrition in NYC” can address significant health disparities that affect different communities. In some communities, especially wealth-deprived communities, there is limited access to affordable healthy food, which leads to a higher rate of diet-related health issues like type II diabetes. By analyzing food access patterns and their relationships with socioeconomic determinants, this project aims to highlight systemic inequalities and raise awareness about equitable health outcomes in NYC.

**The intended final products**  
A web page with:

Main page:  
- Background introduction and site information + a short video intro   
- Research questions   
- Data source introduction  

Data analysis + visualization:  
- Identifying food deserts (Choropleth Maps)   
- Relationship between food and nutrition (Scatter Plots with fitted line)   
- Socioeconomic and demographic factors (Bar Plots/Box Plots)   

Report:  
- Combine analysis and add explanatory details to form a well-structured report  
- Discussion on main findings, policy and community initiatives, and further insights on food access  

The anticipated data sources  
- USDA Food & Nutrition Service government open dataset  
- NYC Open Data  
- NYC Health Community Survey  
- American Community Survey  

**The planned analyses / visualizations / coding challenges**  
Data Cleaning  
- Handling of missing data, reorganizing dataset structures, refining datasets  

Data Analysis  
- Using R packages including `tidyverse`, `ggplot2`, `dplyr`, `tidyr`
- Analyzing effects of covariates such as socioeconomic status, education level, and ethnicity on primary outcomes like food availability in NYC
- Examining and comparing the effectiveness of public health policies on the availability of healthy food sources within NYC

Data Visualization  
- Using violin plots/boxplots to compare food access metrics across income levels or boroughs
- Scatterplots and correlations visualizing the relationship between food access and health outcomes
- Mapping food deserts with demographic overlays using interactive maps
- Discussing findings and insights per visualization

Essential Challenges  
- Ensuring consistency and comparability of visualizations and statistical analyses across datasets
- Balancing clarity and information density in visualizations, especially for multi-layered maps
- Addressing limitations in data sources (e.g., inconsistencies, outdated information) that may affect accuracy

**The planned timeline**  
- **Nov 25:** Draft for website pages  
- **Dec 2:** Final draft for website pages  
- **Dec 4:** Combine results to form the report  
- **Dec 6:** Screencast  
- **Dec 7:** Double check and submission  

